main: pw.tetrafox.juulmc.Main
name: JuulMC
version: 1.1
api-version: 1.13
commands:
  juul:
    description: gives the player a juul
    usage: /juul [amount] [player]
permissions:
  juulmc.*:
    description: grants a player all juulmc permissions
    default: false
    children:
      juulmc.command.use: true
      juulmc.craft: true
  juulmc.command.use:
    description: allows a player to use /juul
    default: op
  juulmc.craft:
    description: allows a player to craft a juul
    default: true